### PR TITLE
Fixed and issue where the script may bail early without disposing of …

### PR DESCRIPTION
**Pull request by mattsw**
I noticed the script was bailing early before disposing so I switched the logic so it will more correctly handle clean up of the objects.

### CODE REVIEW

**Comment by brianary** [comment]
I'll look at it this weekend. I may want to go with a `try { … } finally { … }` block, which seems to be the [preferred methodology](https://technet.microsoft.com/en-us/library/Hh847793.aspx) for freeing resources.

**Comment by mattsw** [comment]
That's fine as well. If that is the case, I can go ahead and submit that request via fork. I was reading that as a preferred methodology but decided to allow the author the freedom to make that choice whilst enhancing the current functionality.

**Comment by mattsw** [comment]
Would you like me to close and revert my local fork?

**Comment by brianary** [comment]
Yeah, go ahead and submit. I need the practice accepting pull requests.

**Comment by mattsw** [comment]
Alright I will go ahead and close this one and make that change. I should have this up before end of day. :)

**Pull request closed without merging**
